spring.application.name=ventas
server.port=8085

# Configuración de Base de Datos PostgreSQL en Neon.tech
spring.datasource.url=jdbc:postgresql://ep-nameless-sun-apibmw55-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_R0PQMJGo6BgU
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true